export const statusList = {

    order_statusList : [
        {
            "orderID" : 1,
            "order_status" : "주문요청",
            "order_store" : "폴바셋 GFC점",
            "address" : "서울특별시 강남구 테헤란로 152 강남파이낸스센터 지하 1층",
            "number" : "070-8998-8984" , 
            "loc_x" : "",
            "loc_y" : "",
            "order_menu" : "아메리카노",
            "imgUrl" : "",
            "BasePrice" : 4700,
            "order_Price" : "",
            "extras" : "샷추가",
            "extras_Price" : 500,
            "cupTypes" : "일회용",
            "cupTypes_Price" : 100,
            "iceHot" : "ICE",
            "size" : "그란데",
            "size_Price" : 500,
            "payment" : "카카오 페이 결제",
            "orderTime" : "2024-08-08",
            "PickupTime" : "2024-08-08"
        },
        {
            "orderID" : 2,
            "order_status" : "픽업완료",
            "order_store" : "폴바셋 GFC점",
            "address" : "서울특별시 강남구 테헤란로 152 강남파이낸스센터 지하 1층",
            "number" : "070-8998-8984", 
            "loc_x" : "",
            "loc_y" : "",
            "order_menu" : "룽고",
            "imgUrl" : "",
            "BasePrice" : 5700,
            "order_Price" : "",
            "extras" : "",
            "extras_Price" : 0,
            "cupTypes" : "매장용",
            "cupTypes_Price" : 0,
            "iceHot" : "ICE",
            "size" : "그란데",
            "size_Price" : 500,
            "payment" : "카카오 페이 결제",
            "orderTime" : "2024-08-05",
            "PickupTime" : "2024-08-06"
        },
        {
            "orderID" : 3,
            "order_status" : "픽업완료",
            "order_store" : "폴바셋 GFC점",
            "address" : "서울특별시 강남구 테헤란로 152 강남파이낸스센터 지하 1층",
            "number" : "" , 
            "loc_x" : "",
            "loc_y" : "",
            "order_menu" : "룽고",
            "imgUrl" : "",
            "BasePrice" : 5700,
            "order_Price" : "",
            "extras" : "",
            "extras_Price" : 0,
            "cupTypes" : "매장용",
            "cupTypes_Price" : 0,
            "iceHot" : "ICE",
            "size" : "그란데",
            "size_Price" : 500,
            "payment" : "카카오 페이 결제",
            "orderTime" : "",
            "PickupTime" : "2024-08-08"
        }
    ]
};
